import pytest

def test_no_user():
    #with pytest.raises(Exception):
    return    
